### ISSUE TITLE
a timeout error on js side

### ISSUE THREAD

**Issue by flufy3d** [Unity-Technologies/furioos-sdk-js#15]
![image](https://user-images.githubusercontent.com/1730604/90246551-2d212000-de35-11ea-8a2e-9b32f774adc9.png)

**Comment by flufy3d** [comment]
but all communication is fine after Session Started

**Comment by flufy3d** [comment]
after I upgrade furioos sdk in npm .solved

**Comment by DonJGo** [comment]
Hi,

This error was not related to the SDK but to Furioos' portal.
It has been fixed in the last release.

Thank you for your report.
Regards
